### ISSUE TITLE
Failed to use set_user_data() on Resource

### ISSUE THREAD

**Issue by Abdillah** [Smithay/wayland-rs#166]
Actually I have difficulty in using this library, or maybe improper usage.

# Use case
I wanted to pass some `MemMap` from server to client thus using user data facilities. In the server, I called `set_user_data` then `get_user_data` in the client. It was segfault, so I suspect either `set_user_data` failed or the user data didn't get passed onto client.

# Usage
I called `set_user_data()` of WlBuffer that passed onto `WlShmPool::create_buffer()`, but after checking WlBuffer's data, I discovered it to be null (both in GDB and LLDB). Thus caused segment fault when I access the data later.

It turned out, `set_user_data()` I called earlier was failed: the data `ptr` will be assigned if only
the WlBuffer (or Resource) structure initialized wiith `Some` data:

```
        fn set_user_data(&self, ptr: *mut ()) {
            if let Some(ref data) = self.data {
                data.1.store(ptr, Ordering::SeqCst);
            }
        }
```

But this buffer is automagically initialized, unfortunately with nulled data.

## Code
I apologize if my code is a mess.
```
    fn create_buffer(&mut self,
        evlh: &mut EventLoopHandle,
        client: &Client,
        resource: &WlShmPool,
        bfrtpl: WlBuffer,
        offset: i32,
        width: i32,
        height: i32,
        stride: i32,
        format: Format
    ) {
        // BufferData impl wl_buffer::Handler
        let bufdata = BufferData::new(self.data.clone(), offset, width, height, stride, format);

        // ..other codes

        let handler_id = evlh.add_handler(bufdata.clone());

        // I inspect bfrtpl with GDB and was null prior assignment

        // assign data
        let bufdata = Arc::new(Mutex::new(bufdata));
        let data = Box::into_raw(Box::new(bufdata));
        bfrtpl.set_user_data(data as *mut ());

        // I inspect with GDB again and was null after assignment

        evlh.register::<WlBuffer, BufferData>(&bfrtpl, handler_id);
    }
```

## Notes
I use older `wayland-rs` `v0.9.9`, but I see the same codes internally. Let me know when you need more snippet. Also let me know when actually I need to upgrade the version since I persistent to upgrade without reason.

Thank you.

**Comment by vberger** [comment]
Hmm, this is using an old version of wayland-server, and the code and API of the library has actually changed a lot since then. I can't force you to upgrade (especially given the amount of work this represent), but we aware that this version line is no longer maintained. wayland-rs is still in a moving state while I'm trying to figure out the most appropriate API (see #165 ).

However, maybe I'm misunderstanding, but you seem to be trying to access `user_data` attached server-side from the client-side ? This is not how `user_data` works nor how it can be used. I allows you to attach a point to a `Resource` and retrieve it from any other handle to the same resource, but in no case is it transferred to the client. These are two different programs, you can't pass pointers around from one to the other. Client and server can only communicate using the protocol messages.

**Comment by Abdillah** [comment]
Ah, I see, `user_data` is only for one-side... and yes I used it for server-client comm too (beside server internal data passing).

Maybe I'll try to upgrade into newer API. But still wonder how the `v0.9.9` store `user_data` since the API `Resource::set_user_data` doesn't store `ptr` when member `data` is null AND there is no direct API to set member `data` non-null, [except by reinitializing from pointer](https://docs.rs/wayland-server/0.9.9/wayland_server/trait.Resource.html#tymethod.from_ptr_initialized) after manually call ffi `wl_resource_set_user_data`.

In newer API, how to correctly store any `user_data`?

**Comment by vberger** [comment]
The `data` member is null when a resource is retrieved that was not created by wayland-server, for example when interacting with a C lib creating its own wayland object (typically the OpenGL stack). In this case, the object is not managed by wayland-server and it may likely already contain some user data that the original creator had set. We cannot change it or it would lead to huge unsafety as the C lib will expect it to remain valid.

If in your case the resource was created by wayland-server, yet it considers it unmanaged, then it is likely a bug of the lib. However it is likely fixed in the newer version, as we are using this mechanism in [smithay](https://github.com/smithay/smithay) everywhere and it works fine.

**Comment by Abdillah** [comment]
Hmm.. so technically this likely has been solved. Close this..
Thank you for your time.
