### ISSUE TITLE
Fundamental API discussion, yet again

### ISSUE THREAD

**Issue by vberger** [Smithay/wayland-rs#228]
So, apparently there is friction with the current API. This API is mostly the result of my use of the libs in smithay and winit, with some other input. I will not claim I have the *best* idea of how the API should be designed, and I'm willing to discuss further the API if people have better ideas. So I'll detail here the trade-offs as I perceive them, as a starting point of the discussion if anyone wants to continue on this (cc @Timidger @Drakulix @YaLTeR @dvc94ch I believe you may be interested in this).

## Lexicon

- a wayland object **interface** is how it is defined in the protocol file. It is a name (eg `wl_buffer`), and a list of messages description. Messages can be **requests** (sent by the client to the server) or **events** (sent by the server to the client), but apart from the name difference they are completely symmetric.
- What I call a wayland object **implementation** is the code that, given a received message, processes it (currently implementations are closures `FnMut(MsgEnum)-> ()`)

## Fundamental required properties

So, the main API question revolves around how messages are *received*. The wayland protocol associates each message to a wayland object, and we have these fundamental properties we want to keep:

- **1)** two wayland objects of the same interface may have different implementation
- **2)** even if two objects have the same implementation, they may use object-specific data
- **3)** it must be possible to share data between an implementation and the rest of the program

Currently, these properties are held like so: each wayland object is independently implemented by a closure, which takes care of **1** and **2** (object-specific data is the closure state). **3** is done by either having `Rc`/`Arc` in the closure state, or using the `user-data` API.

Additionally there are some other properties we need to keep in mind:

- The wayland server **must** process messages from a given client **sequentially** and **in order**.
- A protocol error is always fatal to the wayland connection.
- It should be reasonably easy for users to use protocol extensions, even if they are not part of `wayland-protocols`

## Empirical ergonomic considerations

I've seen and experimented with two main approaches for handling the message reception and processing. Iterator-like, and callback-like.

### Iterator-like API

Event queues are iterator-like constructs that yield `(Object, Message)` tuples, linking each message with a handle to the object it is associated with.

**Pros**:

- works well with rust in general, notably wrt to state sharing (no need for rc or locking)

**Cons**:

- managing object-specific data or implementation require looking up something stored in the object's `user-data` to identify it
- the iterator return type must be able to express all potential messages:
  - this is difficult to integrate with the plug-in way of handling wayland protocols
  - this means the user is likely to have a catch-all arm in their `match`, potentially nullifying the interface-wise exhaustive check depending on how ti is implemented
- the user needs to write a lot of dispatching logic themselves

### Callback-like API based on closures

Each object is independently implemented using a closure receiving an enum describing the possible events of this interface.

**Pros**:

- object-specific logic and data is self-contained in the closure, but can still be factored into sub-functions if needed (that the closure will call)
- plugging in new protocols "just works"

**Cons**:

- sharing state between different objects requires `Arc`/`Rc` and locking mechanisms, which is a lot of boilerplate
  - centralizing the state of a client app can get quite convoluted
- complex logic will need to be delegated into sub-functions, or the closures can get too large to be comfortably readable

### Callback-like API based on traits

Each object is independently implemented using a struct or enum implementing some trait

**Pros**:

- object-specific logic and data is self contained in the type and its implementation

**Cons**:

- plugging-in new protocols is more complex, and require either some boilerplate from the user of `wayland-rs` to declare the protocols to the central machinery (due to coherence rules), or will require a significantly larger fraction of the library code to be generated by `wayland-scanner` and duplicated for each object type.
- sharing state between different objects is as difficult as with closures
- Writing trivial implementations require a lot of boilerplate (defining a type, impl block)

## Unresolved questions

- Is it possible / meaningful to integrate wayland-rs with `Future` / tokio ? If so, how ?

**Comment by YaLTeR** [comment]
### Safe ergonomic single-threaded clients
Another question to address is making it easier to write simple Wayland clients with one event queue which doesn't move between threads. Currently this can be done either by using `Arc<Mutex<_>>` (boilerplate and additional locking which should not be necessary), or by resorting to an unsafe `NewProxy::implement_nonsend()` API. I'd really like to avoid having to write unsafe code for this, especially considering the safety requirements for `implement_nonsend()` (at least as currently documented) aren't easily comprehensible (after thinking about them for a while I'm still not sure I fully understand when it is safe to call the API).

### Trait-based approach PoC
To expand on the trait handling approach, it can be implemented alongside (and even ontop of) the current closure-based approach. Moving over from #229:

I added generation of `EventHandler` traits to `wayland-protocols` with methods corresponding to `Event` enum variants, then added a `Handler<I: Interface>` trait to `wayland-client` to be able to implement a `NewProxy::implement_handler()` trait bounds and hit (presumably) the same trait coherence roadblock (can't implement `Handler<T: EventHandler>` for `T` from crates other than `wayland-client`).

However, I figured out a workaround that doesn't require using complicated macros. I added generation of `EventHandlerWrapper` types which wrap `T: EventHandler` for every object, along with a provided `EventHandler::wrap(self) -> EventHandlerWrapper<Self>` method. This allows to write code like this:
```rust
struct WlRegistryHandler {
    some_state: u32,
}

impl wl_registry::EventHandler for WlRegistryHandler {
    fn global(
        &self,
        proxy: Proxy<WlRegistry>,
        name: u32,
        interface: String,
        version: u32
    ) {
        // Do something, use `self.some_state`, etc...
    }

    // No need to implement everything, default implementations do nothing.
}

fn main() {
    let (display, mut queue) = Display::connect_to_env().unwrap();
    display
        .get_registry(|registry| {
            registry.implement_handler(
                // Use the `wrap()` provided method.
                // Unfortunately, using this requires explicitly importing
                // the EventHandler trait.
                WlRegistryHandler { some_data: 42 }.wrap(),
            )
        })
        .unwrap();
}
```
You can see a full example program that prints out data offers using the `wlr-data-control` protocol [here](https://gist.github.com/YaLTeR/1fac72ee6da826cfd6509f99c0cfef81).

You can find the `wayland-rs` code for this PoC [in this branch](https://github.com/YaLTeR/wayland-rs/tree/event-handler-trait-poc).

This approach is by no means final or ideal. The main issues are:
- Event handler methods accept `&self` instead of `&mut self`. This can be solved by either wrapping it in `Arc<Mutex<_>>` inside `implement_handler()` or providing a specialized single-threaded `implement_handler()`.
- Event handlers must be `Send + Sync`, which, once again, can be solved by either `Arc<Mutex<_>>` or providing a single-threaded `implement_handler()`.
- It's still full of boilerplate like `.wrap()`, `NewProxy`, etc.

### What I'd like the client code to look like
```rust
let registry = display.get_registry().unwrap();
// Optional; if not provided just do nothing for events.
registry.add_listener(WlRegistryHandler { some_data: 42 });
// Or:
registry.add_listener_closure(|event, proxy| { /* ... */ });
```

**Comment by Timidger** [comment]
I'll explain briefly how wlroots-rs is built, and why I made the trade offs I did. I don't think the wlroots-rs design should be duplicated here, since we are solving different problems, but it might be helpful knowledge anyways.

Like you I went through many decision iterations on wlroots-rs and the one I narrowed down on is a callback-like API based on traits.To address the cons you pointed out, and why they don't apply to wlroots-rs in particular:

* wlroots provides a lot of plug-and-play, already implemented protocols. Because of this most protocols the compositor would need don't need be custom added, and for the ones that do the boilerplate is a one-time cost and would have been no better if it had been done in C. You might have a different design ethos for smithay, and especially this especially isn't viable for the client side of your library.
* Sharing state is accomplished by a "super" state stored in [a Compositor struct](http://way-cooler.org/docs/wlroots/compositor/struct.Compositor.html) This state is passed to all callbacks in the form of [a handle](http://way-cooler.org/docs/wlroots/compositor/struct.Handle.html) that can be upgraded to access the state (stored as an `Any` since generics would have to cascade throughout the entire library otherwise). So instead of a more Smalltalk like message passing it's more usual imperative state transformations done on some data based on events.
  + A side note on this. wlroots-rs is not thread safe and probably never will be. Partly this is because wlroots is not thread safe, as far as I'm aware. The compositor is also globally stored in a pointer internal to the library and the manager handlers are allocated statically as well to avoid dynamic allocation at startup time. A single thread is enough for wlroots-rs case since it relies on wlroots so much it doesn't need to implement as many things. At the same time it has been found that a single thread is sufficient for implementing a Wayland compositor, especially when combined with epoll if other event loops are used (e.g. DBus, glib, etc.)
* Writing a struct definition and then an impl is not that much boilerplate, and is only done once per implementation. In the compositor case, there's usually only one implementation though it depends on the object of course. In particular all of the traits have a default implementation to do nothing in wlroots-rs (I believe it's the same in wayland-rs?) so it can just be an empty impl if necessary.

Though Way Cooler is currently on hiatus, you can see what the resulting code looks like in this kinda-working compositor: https://github.com/way-cooler/way-cooler/tree/master/way-cooler/src.

Ultimately I have no dog in this fight, since I mainly use the unsafe bindings you expose which are unlikely to change. If I work on Way Cooler again this will affect me again when I write the awesome client, but since that's a ways off I have nothing else to contribute.

**Comment by YaLTeR** [comment]
I'd also like to add that it's kinda inconvenient having to import all the different `RequestTrait`s and having to rename all of them as the result so they don't clash. I suppose the "generating a significantly larger portion of the code as part of `wayland-scanner`" could solve this too (by having appropriate methods on object structs themselves as opposed to using `Proxy<_>`)?

**Comment by vberger** [comment]
Thanks for your feedback on that. Additional discussion occurred in the chatroom and I'll summarize here the point we reached:

Following @YaLTeR 's idea, which manages to run the handler-based approach with minimal boilerplate (importing the trait and the `.wrap()` call), it might be worth pursuing not choosing between these 3 paradigms.

This could be done like this (which has quite some similarities with the previous APIs). I describe the client-side API, server-side would be very similar.

Have a general `Handler` trait:

```rust
trait Handler<I: Interface> {
    fn receive(&mut self, event: I::Event, proxy: Proxy<I>);
}

impl<I: Interface> NewProxy<I> {
    fn implement<H: Handler<I>>(self, handler: H) -> Proxy<I> { ... }
}
```

The `Handler` trait would have a blanket impl for closures:

```rust
impl<I: Interface, F> Handler<I> for F where F: FnMut(I::Event, Proxy<I>) {
    fn receive(&mut self, event: I::Event, proxy: Proxy<I>) {
        (*self)(event, proxy)
    }
}

// this convenience method is added on `NewProxy` because of rust's inference failure
impl<I: Interface> NewProxy<I> {
    fn implement_closure<F: FnMut(I::Event, Proxy<I>)>(self, handler: F) -> Proxy<I> {
        self.implement(handler)
    }
}
```

This may leave the room open for also designing an event-sink like API allowing to convert some of the proxies into an event iterator, depending on which is more convenient. The main idea would thus to offer a "take what you prefer" API.

Additionally, it might be possible to add some runtime tracking to make `implement_nonsend` safe. This could be done by tracking which thread owns the event queue associated with each proxy, and panicking if the user tries to implement the proxy from the wrong thread. If we manage that, then the default `implement` method would be the non-threadsafe one (as it is basically what people need most of the time anyway), and there would be an `implement_threadsafe` method added.

Also, as suggested by @trimental, we could add a `implement_dummy()` method that implements the proxy so that it ignores all the messages it receives. This would be more ergonomic than `.implement_closure(|_,_| {})`, for prototyping and cases when the client needs an object to exist bu does not actually care which events it receives.

**Comment by YaLTeR** [comment]
Update on my trait PoC.

I managed to sidestep the whole coherency issue without having to resort to `EventHandlerWrapper` and a `.wrap()` method by "reversing" the `Handle<I: Interface>` trait into a `HandledBy<T>` trait. Instead of needing to implement, say, `Handle<WlDisplay> for T where T: EventHandler`, which is not allowed due to coherency, we can implement `HandledBy<T> for WlDisplay where T: EventHandler`, which is perfectly legal.

Updated branch: [here](https://github.com/YaLTeR/wayland-rs/tree/event-handler-trait-poc-2).
Updated example code: [here](https://gist.github.com/YaLTeR/ca0c8774e5baec3a98e136c89eee62e3).
Changes in the example code:
- Removed all `.wrap()` calls as they are no longer needed.
- Removed all `EventHandler` trait imports as they are no longer needed.

**Comment by vberger** [comment]
@YaLTeR This is quite a nice find! And it seems this approach works better with inference also, possibly removing the need for a `implement_closure()` method.

This also means that the transition would be completely painless, which is a nice plus to have.

the only downside I see, is that it is no longer possible for downstream crates to implement directly `HandledBy<I>` (while `Handler<I>` could be), but I don't know if that is something that would actually be missed.

**Comment by vberger** [comment]
To combine with all that, I had in mind some way to insert adapters to convert this callback-like API into an iterator like one, using event sinks, basically a non-threadsafe version of a MPSC, such that the sink is cloneable with an API like:

```rust
#[derive(Clone)]
struct EventSink<E> { ... }

struct EventIter<E> { ... }

fn make_event_iterator<E>() -> (EventSink<E>, EventIter<E>) { ... }

impl Iterator for EventIter<E> {
    type Item = E;
}

impl<E> HandledBy<EventSink<E>> for Interface where E: From<(Interface, Iterface::Event)> { ... }
```

And a macro that allows the user to quickly create an enum to fill in the `E` type parameter:

```
event_union!(XdgSurface, XdgToplevel, ...)

// which expands to

enum Events {
    XdgSurfaceEvent(XdgSurface, XdgSurface::Event),
    XdgToplevelEvent(XdgToplevel, XdgToplevel::Event),
    ...
}

impl From<(XdgSurface, XdgSurface::Event)> for Events { ... }

impl From<(XdgToplevel, XdgToplevel::Event)> for Events { ... }
```
