### ISSUE TITLE
`WAYLAND_DISPLAY` and `WAYLAND_SOCKET` are apparently not universal

### ISSUE THREAD

**Issue by icefoxen** [Smithay/wayland-rs#282]
I was experimenting with `winit` on Wayland, which naturally uses this lib, and got some weird behavior.  Namely, on Weston it worked just fine, but trying to run my program in `mutter --nested --wayland` made it panic with `NoCompositorListening`.  Turns out that `mutter` doesn't seem to set a `WAYLAND_DISPLAY` environment variable, and neither of the two seemed to set `WAYLAND_SOCKET`, which is called out in the source as the other alternative.  Setting `WAYLAND_DISPLAY` by hand made it work fine.

So this may be a bug in Mutter, or it might have just never set this var correctly when trying to run it in nested mode on X11 with no... uh, whatever the "window manager" equivalent in Wayland is.  So what I'm really asking is... are these env vars the Right Way to find your Wayland socket?  Should this bug be punted upstream to Mutter?  Or am I misunderstanding something?

**Comment by vberger** [comment]
`WAYLAND_DISPLAY` is considered the standard way for a compositor to advertise the socket address to its clients. So if mutter does not set it itself, it is likely that something else does so in the Gnome stack normally.

Though a quick grep in mutter's source code seems to show it actually sets it? https://gitlab.gnome.org/GNOME/mutter/blob/master/src/wayland/meta-wayland.c#L452

**Comment by YaLTeR** [comment]
Actually reading the [docs](https://wayland.freedesktop.org/docs/html/ch04.html#sect-Protocol-Wire-Format) it would seem that if `WAYLAND_DISPLAY` is unset, then `wayland-0` should be used? Not sure.

**Comment by vberger** [comment]
This is actually something that has been discussed some time ago on the wayland-devel mailing lists (starting from this mail: https://lists.freedesktop.org/archives/wayland-devel/2015-August/023909.html).

Basically, the `wayland-0` fallback is an historical behavior of the wayland C lib, which has undesirable consequences. For example, if you have a nested wayland session started in your X11 session, launching a wayland-aware app in X11 would make it actually start in the nested wayland session, because of the fallback.

So, a majority of people agree that this fallback is a Bad Idea™, but it stays here for retro-compatibility, and because apparently the Gnome project hates environment variables for some reason.

**Comment by icefoxen** [comment]
Awesome, thank you for the background!  I shall carry my investigations onward into Mutter then.
