### ISSUE TITLE
WlBuffer start and end access

### ISSUE THREAD

**Issue by nifker** [Smithay/wayland-rs#292]
Ive run into a problem where I get the following error: "wayland-client protocol error 2 on object wl_buffer@17 error accessing shm buffer" - even though I am not sure if this has to do with the error, I have seen that libwayland-client has these functions, which could solve the issue:

void wl_shm_buffer_begin_access (struct wl_shm_buffer *buffer)
void wl_shm_buffer_end_access (struct wl_shm_buffer *buffer)

How can I achieve the same with this crate(if related to the issue)?

**Comment by vberger** [comment]
This error suggests that the file descriptor backing your `wl_buffer` could not be used by the compositor. Are you using SHM pool to draw your contents? If so you need to ensure that the file descriptor sent to the server can be used by it and is valid. It is difficult to say what the problem is exactly without more information about what you are doing.

The simplest way to achieve this would be to use [SCTK](https://github.com/Smithay/client-toolkit/) which provides the `MemPool` and `DoubleMemPool` abstractions for just that.

The functions you brought up here are actually part of libwayland-**server** API, so will not be of any help to you if you are writing a client app.

**Comment by nifker** [comment]
@vberger yes I am using tempfile for drawing, this doesnt happen instantly when drawing to the surface, just not really predictable sometimes.
But Ill definitely try the MemPool as I did it before myself.
Oh I havent seen that.

**Comment by nifker** [comment]
Ill close this for now.
