### ISSUE TITLE
Wayland-cursor Segmentation fault

### ISSUE THREAD

**Issue by nifker** [Smithay/wayland-rs#293]
When a Cursortheme is dropped I get a SIGSEGV the backtrace shows me this call: https://smithay.github.io/wayland-rs/src/wayland_cursor/lib.rs.html#114-120

**Comment by vberger** [comment]
Do you have some small code that reproduces the issue?

**Comment by nifker** [comment]
It doesnt seem to be easy to recreate I will for point to the to the lines where I use it.
https://github.com/nifker/rust_minifb/blob/e02ea07b80617df95eb8497fe5ee072700fce1a6/src/os/unix/wayland.rs#L198-L204
As well as L588 and L142

**Comment by vberger** [comment]
Hmm, this is going to be tricky to investigate.

Does your code consistently reproduce the segfault? Would I need to do some specific manipulation to reproduce it using your code?

Alternatively, a full backtrace with debug symbols (including those of libwayland-cursor and libwayland-client) would certainly help a lot.

**Comment by nifker** [comment]
Yes it seems to do it all the time, as one user could approve it too. Not really you can just use the  constructor Window::new() and let the application close.

**Comment by nifker** [comment]
How do I get the debug symbols from wayland-rs?

**Comment by vberger** [comment]
They should be there if you built your project in debug mode.

For the symbols of the system wayland libraries, you need to install them on your system. The procedure will depend on your distribution.

**Comment by vberger** [comment]
Okay, I got to the bottom of this (thanks `valgrind`).

So, the main issue is that in your program, the `Display` is dropped before the `CursorTheme`. When the `Display` is dropped, the whole state of the wayland connection is cleared, which means that then, when the destructor of `CursorTheme` runs, it runs on freed memory, which of course is a very bad thing.

So, this is clearly an issue with `wayland-rs`, but I'm really not sure about how it can be solved in a reasonable way.

A quickfix for you would be to change the order of fields in your `DisplayInfo` struct so that `_display` is last.

**Comment by vberger** [comment]
Actually, I'll be closing this in favor of #294.
