### ISSUE TITLE
AsRawFd and hide guard

### ISSUE THREAD

**Issue by Matthias-Fauconneau** [Smithay/wayland-rs#305]
Would be nice if EventQueue:

had AsRawFd
`
impl std::os::unix::io::AsRawFd for EventQueue { 
fn as_raw_fd(&self) -> i32 { self.display().get_connection_fd() }
 }
`

hid the guard with a simple method which would also Err(WouldBlock) on concurrent reads
`
        impl EventQueue {
            #[throws(io::Error)]
            fn pull(&self) {
                self.prepare_read().ok_or(Err(io::WouldBlock))?.read_events()
            }
       }
`
Most users are not running concurrent threads per queue anyway and even the edge case probably can't do anything more meaningful about the contention.

**Comment by vberger** [comment]
I'm not sure I want to implement `AsRawFd` for `EventQueue`, as I don't feel it meets the general definition of the trait, given this FD should not be used for anything except registering it to a polling mechanism (as is described in the `get_connection_fd()` method). Implementing the trait would make this documentation warning almost invisible.

Regarding `prepare_read()`, it seems you misunderstood the meaning of its return value. If it returns `None`, this means that the current event queue still has events in its internal buffer, and that these events should be dispatched before trying to read from the socket. This API is overall a direct translation of the API of the system `libwayland-client`. This is used to avoid unnecessary reads on the socket if multiple event queues try to read it concurrently, so that only one thread will actually perform the `read` system call. See also #223

**Comment by Matthias-Fauconneau** [comment]
Okay, that's your call. I think that it's okay to require user to read the struct documentation when using such a bare metal trait, on the other hand, requiring a newtype is okay too.
Ideally we'd have a trait with a specialized contract something like :
```
mod nix {
            struct RawPollFd(std::os::unix::RawFd);
            pub trait AsRawPollFd {
                fn as_raw_poll_fd(&self) -> RawPollFd;
            }
            impl AsRawPollFd for AsRawFd { unsafe fn as_raw_poll_fd(&self) -> RawPollFd { RawPollFd(self.as_raw_fd().0) } }
        }
        struct Async;
        impl Async {
            fn new(poll_fd: impl AsRawPollFd) -> Result<smol::Async> {
                struct AsRawFd<T>(T);
                impl std::os::unix::io::AsRawFd for AsRawFd { fn as_raw_fd(&self) -> RawFd { self.as_raw_poll_fd().0 /*->smol::Reactor*/ }
                smol::Async::new()
            }
        }
        impl nix::AsRawPollFd for client::EventQueue { fn as_raw_poll_fd(&self) -> RawPollFd { RawPollFd(self.display().get_connection_fd()) } }
```
Lot of shimming when both sides don't share a trait, not sure which common crate (nix?) could host that.

Thanks! I got confused reading the comments as applying to the next line ><
```
// 1. read events from the socket if any are available
            if let Some(guard) = self.queue.prepare_read() {
                // might be None if some other thread read events before us, concurently
                if let Err(e) = guard.read_events() {
                    if e.kind() != io::ErrorKind::WouldBlock {
                        return Err(e);
                    }
                }
            }
```
So if the correct logic is prepare_read()?.read_events()? that's already simple enough :)
