### ISSUE TITLE
Align wayland-cursor heuristic for choosing size on libwayland's

### ISSUE THREAD

**Issue by vberger** [Smithay/wayland-rs#373]
Currently we are using a different logic, which causes us to choose differently in some cases.

For example, if the requested size is 50 but the theme only provides 32 and 64, we choose the 32 while libwayland chooses the 64.

**Comment by psychon** [comment]
Since I was wondering about the details of the algorithms:
Xcursor files are complicated. There are separate fields for `width`, `height`, and `size` for a cursor.

For a wanted size of `wanted`:
- wayland-rs uses the size that minimises `(wanted * wanted - width * height).abs()`: https://github.com/Smithay/wayland-rs/blob/b01315eaaf9023902d2816fd44e8d6942ed9a8ac/wayland-cursor/src/lib.rs#L196-L211
- libwayland copies code from libXcursor and that one loads the entry that minimises `(wanted - size).abs()` (no squaring here): https://github.com/wayland-project/wayland/blob/ddf21afa6ee99ad6a00705cc74b62a1c4907776b/cursor/xcursor.c#L405-L428

It looks like the `size` field is actually public in the xcursor-rs crate and can just be used directly.

Also, slightly related, I recently-ish wrote some code for parsing Xcursor files: https://github.com/psychon/x11rb/blob/master/src/cursor/parse_cursor.rs
the "internal public" API is just the following function:
```rs
pub(crate) fn parse_cursor<R: Read + Seek>(
    input: &mut R,
    desired_size: u32,
) -> Result<Vec<Image>, Error> {
```
Perhaps I should have checked first whether there is already a crate for this (apparently there is).

**Comment by vberger** [comment]
I didn't realize there is a `size` field in addition to the actual width and height of the image. Of course this is what we should be using.
