### ISSUE TITLE
Why `wl_pointer::Event` is not `Copy` or `Clone`

### ISSUE THREAD

**Issue by Aetf** [Smithay/wayland-rs#409]
I'm piping the event to a broadcast channel, it'd be really handy if the event implements `Clone`.

I checked the source code and didn't see anything preventing that. Am I missing something?

**Comment by WhyNotHugo** [comment]
Note that [std::os::unix::io::FromRawFd::from_raw_fd](https://doc.rust-lang.org/std/os/unix/io/trait.FromRawFd.html#tymethod.from_raw_fd) is already unsafe, so cloning the `fd` is likely "no unsafe".

That said, pointer events don't pass any file descriptors, that's keyboard events.

**Comment by vberger** [comment]
> That said, pointer events don't pass any file descriptors, you're probably thinking of keyboard events.

Well, I'm thinking about all events. As this code is auto-generated by `wayland-scanner` it's kind of an all-or-nothing situation, either all event enums are `Clone`, or none are.

**Comment by ids1024** [comment]
Wayland-rs now generates `Event` enums with `OwnedFd` instead of `RawFd`, so it's definitely not possible to derive clone in that case.

Wayland-scanner could add `Clone` only if all events could be cloned, but that would be a backwards compat issue if a new protocol version added an event with an fd.

But I don't think there's any reason you can't use something like `Arc<wl_pointer::Event>` and send that over a broadcast channel.

So this doesn't really seem viable or necessary. As far as I can tell.
