### ISSUE TITLE
zwlr_output_head_v1::Event::CurrentMode event seems unusable.

### ISSUE THREAD

**Issue by james-lawrence** [Smithay/wayland-rs#415]
attempted to use it to detect the current mode of a display and it can't be compared to the objects returned in the mode events.
nor can you attach to the object to retrieve its configuration.

I might be missing something though.

**Comment by vberger** [comment]
I'm not sure I get the issue, the `zwlr_output_head_v1.mode` event provides a `zwlr_output_mode_v1` object, which is then referenced by the `zwlr_output_head_v1.current_mode` event. Those object should be comparable through `PartialEq`.

Furthermore, a natural path would be for the `zwlr_output_mode_v1` handler to store its configuration in the object's user-data, so that the details of the configuration can then be accessed from any part of the program that has an instance of it available.
