### ISSUE TITLE
0.30 sys backend audit with valgrind

### ISSUE THREAD

**Issue by i509VCB** [Smithay/wayland-rs#448]
Ran all the tests in the project in valgrind assuming that #447 is merged:

https://gist.github.com/i509VCB/81726a541c2fe96e1446ff7c2fbc77b3

There are three types of leaks I've found while analyzing the log:

## Client
- `wl_proxy_marshal_array_constructor_versioned` inside `Handle::send_request`.
- `wl_display_read_events` inside `Handle::try_read`

## Server
- `Handle<D>::create_global`
  - globals are not destroyed at `drop` time.

**Comment by vberger** [comment]
> `wl_proxy_marshal_array_constructor_versioned` and `wl_display_read_events`

Those ones is use leaking every wayland object that was not explicitly destroyed by protocol messages, because contrarily to its documentation, `wl_display_disconnect` does *not* "free all resources" associated with the connection. Not quite sure what to do about that, tracking all wayland objects to properly destroy them on drop would add significant overhead.

> `Handle<D>::create_global`

Indeed, there are no "global destructrors" in libwayland, so we should probably track them to properly free them.

**Comment by vberger** [comment]
According to https://gitlab.freedesktop.org/wayland/wayland/-/issues/4

it looks like the client-side thing is expected behavior:

> when a wl_display is destroyed, all objects, event queues etc. referencing it have already been destroyed
