### ISSUE TITLE
Display parsing error under flatpak

### ISSUE THREAD

**Issue by Doomsdayrs** [Smithay/wayland-rs#597]
https://github.com/YaLTeR/wl-clipboard-rs/issues/32

This was a fun journey of 3 hours, Somewhere past this [line](https://github.com/Smithay/wayland-rs/blob/4f3e307d181243f86e60979c8a7e252c16250ed0/wayland-client/src/conn.rs#L72) breaks down under flatpak.

**Comment by vberger** [comment]
Sorry for the late reply. The message you're linking is confusing, because I have no idea where the "Display parsing error" message is coming from, which makes its quite difficult to understand what happens.

So my questions would be:

1. Is this problem still relevant ?
2. If yes, what versions of the crates are used when you reproduce them (at least `wl-clipboard-rs` and `wayland-client` ?
3. Could you provide the full output of running the program with the env variable `WAYLAND_DEBUG=1` ?

**Comment by Doomsdayrs** [comment]
The late reply is okay!

The problem still occurs, but I was misidentifying the issue!

Sorry for any headache, and stay well!
